---
layout: archive
title: Lean Prover Zulip Chat Archive 
permalink: archive/144837PRreviews/49740923ringofctufunctions.html
---

<h2>Stream: <a href="https://leanprover-community.github.io/archive/144837PRreviews/index.html">PR reviews</a>
<h3>Topic: <a href="https://leanprover-community.github.io/archive/144837PRreviews/49740923ringofctufunctions.html">#923 ring of ctu functions</a></h3>

<hr>

<base href="https://leanprover.zulipchat.com">
{% raw %}
<a name="163362822"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/144837-PR%20reviews/topic/%23923%20ring%20of%20ctu%20functions/near/163362822" class="zl"><img src="https://leanprover-community.github.io/assets/img/zulip2.png" alt="view this post on Zulip"></a> <a href="https://leanprover-community.github.io/archive/144837PRreviews/49740923ringofctufunctions.html#163362822">Johan Commelin (Apr 15 2019 at 08:45)</a>:</h4>
<p><a href="https://travis-ci.org/leanprover-community/mathlib/jobs/520147971" target="_blank" title="https://travis-ci.org/leanprover-community/mathlib/jobs/520147971">https://travis-ci.org/leanprover-community/mathlib/jobs/520147971</a> is complaining about names already existing in the environment. Is this an example of malfunctioning caches?</p>


{% endraw %}
